export const USER_LIST_LOADING = 'USER_LIST_LOADING';
export const SAVE_USER_LIST = 'SAVE_USER_LIST';
export const ADD_USER_LOADING = 'ADD_USER_LOADING';
export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const ALTER_USER_ORDER = 'ALTER_USER_ORDER';
export const SELECT_USER = 'SELECT_USER';
export const TOGGLE_USER_DETAILS = 'TOGGLE_USER_DETAILS';
export const TOGGLE_USER_ADD = 'TOGGLE_USER_ADD';

